#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="yabai -m rule --apply"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --apply

yabai -m config                                 \
    mouse_follows_focus          on            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_opacity_duration      off            \
    active_window_opacity        1.0           \
    normal_window_opacity        1.0          \
    window_opacity               off            \
    insert_feedback_color        off    \
    window_border_width          3.5              \
    window_border_radius         12             \
    window_border_blur           on            \
    window_border_hidpi          on             \
    window_border                on            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  24             \
    bottom_padding               24            \
    left_padding                 24             \
    right_padding                24             \
    window_gap                   16             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


yabai -m rule --add label="^Kalkulator$" app="^Kalkulator$" manage=off
yabai -m rule --add label="^Ustawienia systemowe$" app="^Ustawienia systemowe$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Dom" app="^Dom$" manage=off
yabai -m rule --add label="DeepL" app="^DeepL$" manage=off
yabai -m rule --add label="Fork" app="^Fork$" manage=off
yabai -m rule --add label="Wiadomości" app="^Wiadomości" manage=off
yabai -m rule --add label="Safari" app="^Safari$" manage=off
yabai -m rule --add label="ColorSlurp" app="^ColorSlurp$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="Preferencje systemowe" app="^Preferencje systemowe$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app=".*" layer=normal


echo "yabai configuration loaded.."

#
# setup spaces
#
#yabai -m space 1 --label web
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 term
setup_space 2 web
setup_space 3 teams
setup_space 4 code

hyper - y : yabai --restart-service | yabai -m rule --apply

yabai -m rule --add app="^WezTerm$" space=^term
yabai -m rule --add app="^Arc$" space=^web
yabai -m rule --add app="^Microsoft Teams$" space=^teams
yabai -m rule --add app="^IntelliJ IDEA$" space=^code



