#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#
#    adding animation ?!

#    window_animation_frame_rate  120            \

#
##//DEBUG
yabai -m config debug_output on

#
#
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# active_window_border_color   0xff222222 \
# normal_window_border_color   0xff222222    \

yabai -m config                                 \
    mouse_follows_focus          on            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_opacity_duration      off            \
    active_window_opacity        1.0           \
    normal_window_opacity        1.0          \
    window_opacity               off            \
    insert_feedback_color        off    \
    window_border_width          3.5              \
    window_border_radius         12             \
    window_border_blur           on            \
    window_border_hidpi          on             \
    window_border                on            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  24             \
    bottom_padding               24            \
    left_padding                 24             \
    right_padding                24             \
    window_gap                   16             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


yabai -m rule --add app="^Microsoft Teams$" title="^Microsoft Teams Notification$" manage=off
yabai -m rule --add app="^Ustawienia systemowe$" title="^Ustawienia systemowe$" manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Dom" app="^Dom$" manage=off
yabai -m rule --add label="DeepL" app="^DeepL$" manage=off
yabai -m rule --add label="Fork" app="^Fork$" manage=off
yabai -m rule --add label="Wiadomości" app="^Wiadomości" manage=off
# yabai -m rule --add label="Slack" app="^Slack" manage=off
yabai -m rule --add label="Safari" app="^Safari$" manage=off
yabai -m rule --add label="ColorSlurp" app="^ColorSlurp$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="Preferencje systemowe" app="^Preferencje systemowe$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app=".*" layer=normal


echo "yabai configuration loaded.."

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}


setup_space 1 emacs
setup_space 2 code
setup_space 3 web
setup_space 4 social
setup_space 5 media
setup_space 6 other

# move some apps automatically to specific spaces
# yabai -m rule --add app="^Code$" space=^1
# yabai -m rule --add app="^Obsidian$" space=^1
# yabai -m rule --add app="^Chrome$" space=^3
# yabai -m rule --add app="^Slack$" space=^4
# yabai -m rule --add app="^Youtube Music$" space=6
# yabai -m rule --add app="^iTerm2$" space=5



# borders active_color=0xff999999 inactive_color=0xff444444 width=5.0 &

